fix mobile safari scale bug
francoischalifour/medium-zoom pull request #172
Opened 2021-05-03 15:46 UTC by nabettu

## Summary

fixed this issue on mobile safari zoomed image blurry. #151
https://github.com/francoischalifour/medium-zoom/issues/151

## Result

It does not use "transform scale" but instead sets width and height.

2021-05-04 07:33 UTC, francoischalifour requested changes
Hey, thanks for your contribution!

We actually want to **animate only compositor properties**. The `width` and `height` properties trigger paints, and browsers are unable to animate those efficiently.

You can learn more in [**Stick to Compositor-Only Properties and Manage Layer Count**](https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count).

We can't move forward with this fix unfortunately.

2021-05-04 07:33 UTC, closed without merging

2021-05-04 07:38 UTC, nabettu commented
@francoischalifour
OK. Thanks for considering this PR!
The best thing is that safari itself addresses this issue, so wait for it.

2021-06-02 23:18 UTC, flekschas commented
Too bad this doesn't get addressed. Thanks for the work anyway!

> The best thing is that safari itself solves this issue, so wait for it.

Do you mind elaborating? :) Is a new version of Safari going to fix this? I am curious because currently this library not useful for iOS given the bug.

2024-06-01 16:00 UTC, AdrianFahrbach commented
@francoischalifour Any updates on this? It is still an open issue (#151) and makes this package unusable for my use cases.

Maybe only applying this fix on Safari browsers as a fallback would be a solution?
I get your efficiency doubts, but we are talking about a single, short animation, so I think this shouldn't lead to performance issues.